services:
  - type: web
    name: itguess
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -c "from app import app, db; from flask import current_app; app.app_context().push(); db.create_all()"
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.12
      - key: PYTHONPATH
        value: .
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
    plan: free
    branch: master
    healthCheckPath: /health
    autoDeploy: true
    domains:
      - itguess.onrender.com
