services:
  - type: web
    name: itguess
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: PYTHONPATH
        value: .
    plan: free
    branch: main
    healthCheckPath: /
    autoDeploy: true
