services:
  - type: web
    name: itguess
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.12
      - key: PYTHONPATH
        value: .
    plan: free
    branch: main
    healthCheckPath: /
    autoDeploy: true
